version: '3.8'

services:
  db:
    image: 'bitnami/postgresql:16.3.0-debian-12-r17'
    ports:
      - 5433:5432
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: pass
      POSTGRESQL_MAX_CONNECTIONS: 300

    
